image: node:latest
stages:
  - release

npm-publish:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - npm install
  script:
    - echo "Publishing to NPM."
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm run build
    - npm run release
